### ISSUE TITLE
build mechanoid

### ISSUE THREAD

**Issue by hannesa2** [robotoworks/mechanoid#265]
When I clone and build mechanoid by my own (last commit Fri Jan 09 2015 2f2d4175b12)

    ./build product
    cp target/lib/mechanoid-sources.jar ~/dev/App/libs/
    cp target/lib/mechanoid.jar ~/dev/App/libs/

mechanoid doesn't generate getContentUri()

    public abstract class ActiveRecordFactory<T extends ActiveRecord> {
        ...
        public abstract Uri getContentUri();

public class AllPoiRecord extends ActiveRecord implements Parcelable {

	private static ActiveRecordFactory<AllPoiRecord> sFactory = new ActiveRecordFactory<AllPoiRecord>() {
		@Override
		public AllPoiRecord create(Cursor c) {
			return fromCursor(c);
		}
		
		@Override
		public String[] getProjection() {
			return PROJECTION;
		}
	};

**Comment by hannesa2** [comment]
I see it's happen with https://github.com/robotoworks/mechanoid/commit/881515a0ab30c7d6cfe3ca94de52a986f53b3964

**Comment by fluxtah** [comment]
Hey sorry about this not been on top of Mechanoid recently, this should be fixed I believe

**Comment by hannesa2** [comment]
I used the most recent version 2d1ef6e but run 

    ./build product 

causes a lot of errors

> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.22.0:compile (default-compile) on project com.robotoworks.mechanoid.db.ui: Compilation failure: Compilation failure:
> [ERROR] /Users/hannes/git/mechanoid/plugins/com.robotoworks.mechanoid.db.ui/src-gen/com/robotoworks/mechanoid/db/ui/contentassist/antlr/internal/InternalSqliteModelParser.java:[11]
> [ERROR] import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
> [ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [ERROR] Access restriction: The type 'AbstractInternalContentAssistParser' is not API (restriction on classpath entry '/Users/hannes/.m2/repository/p2/osgi/bundle/org.eclipse.xtext.ide/2.8.1.v201503230617/org.eclipse.xtext.ide-2.8.1.v201503230617.jar')
> [ERROR] /Users/hannes/git/mechanoid/plugins/com.robotoworks.mechanoid.db.ui/src-gen/com/robotoworks/mechanoid/db/ui/contentassist/antlr/internal/InternalSqliteModelParser.java:[12]
> [ERROR] import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
> ... and much more ....

I see you use most recent xtext version 2.8.1, can I do something or do I have to wait ?

**Comment by hannesa2** [comment]
76b0681919 seems to be the last compilable commit
